export const CHECK_BOOKING_REQUEST = "CHECK_BOOKING_REQUEST";
export const CHECK_BOOKING_SUCCESS = "CHECK_BOOKING_SUCCESS";
export const CHECK_BOOKING_FAIL = "CHECK_BOOKING_FAIL";
export const CHECK_BOOKING_RESET = "CHECK_BOOKING_RESET";

export const BOOK_DATES_SUCCESS = "BOOK_DATES_SUCCESS";
export const BOOK_DATES_FAIL = "BOOK_DATES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";